version: '3.7'

services:
  # MySQL Database
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: yii2db
      MYSQL_USER: yii2user
      MYSQL_PASSWORD: yii2password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - yii2_network

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - yii2_network

  # PHP
  php:
    image: php:7.4-fpm
    container_name: php
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
      - php_logs:/var/log/php
    networks:
      - yii2_network
    depends_on:
      - mysql
      - rabbitmq

  # Nginx
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - yii2_network
    depends_on:
      - php

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    networks:
      - yii2_network
    depends_on:
      - mysql
volumes:
  mysql_data:
  php_logs:

networks:
  yii2_network:
    driver: bridge
